version: '3.4'

services:
  screamerdb:
    container_name: screamerdb
    image: postgres:13.1
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: screamer
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  #Used for updating database
  liquibase:
    container_name: pg_updater
    image: liquibase/liquibase:4.7.0
    volumes:
      - ./liquibase:/liquibase/changelog
    command: liquibase --url="jdbc:postgresql://screamerdb:5432/screamer" --changeLogFile=/changelog/changelog.sql --username=admin --password=admin update
    depends_on:
      - screamerdb

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - screamerdb
    ports:
      - "5050:80"

  screamer.webapi:
    image: ${DOCKER_REGISTRY-}screamer
    environment:
      - DB_CONNECTION_STRING=host=screamerdb;port=5432;database=screamer;username=admin;password=admin
    build:
      context: .
      dockerfile: Screamer.WebApi/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - screamerdb
